### ISSUE TITLE
IP blacklist does not seem to filter correctly

### ISSUE THREAD

**Issue by paberr** [nimiq-network/core#155] opened 2017-06-09 12:08 UTC
We still try to establish a connection to 127.0.0.1 if advertised so.
> WebSocket connection to 'wss://127.0.0.1:12345/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by styppo** [comment] 2017-12-16 03:45
Duplicate of #13.

**Closed by styppo** 2017-12-16 03:45 UTC
