### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by junw3i** [nimiq-network/core#296] opened 2018-01-03 11:06 UTC
`npm install` fails on the core folder as dependency library link is broken.

https://github.com/level/leveldown/releases/download/v1.9.0/leveldown-v1.9.0-node-v59-linux-x64.tar.gz has been removed in their github.

Error message output:
```
prebuild-install http 404 https://github.com/level/leveldown/releases/download/v1.9.0/leveldown-v1.9.0-node-v59-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=9.3.0 runtime=node arch=x64 platform=linux)
```

**Comment by Azard** [comment] 2018-01-03 20:18
me too

**Comment by paberr** [comment] 2018-01-12 17:40
This will be fixed when updating the version of levelup/leveldown used in the next version of JungleDB.
Also see: https://github.com/nimiq-network/jungle-db/pull/17

We'll most likely release the next version of the JungleDB together with the next version of the Nimiq core.
In the meanwhile, you can replace
https://github.com/nimiq-network/core/blob/2c2fab0150b41c716701100b6cddf0e11cf4d6cd/package.json#L36
by `"jungle-db": "nimiq-network/jungle-db#paberr/update-packages",`, which probably fixes the issue.

**Comment by jsappme** [comment] 2018-03-06 20:32
Any idea why this error when trying to run npm install, I never had it before?

```
npm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > uws@9.14.0 install /home/nimiq/.npm/_cacache/tmp/git-clone-f05fd6e2/node_modules/uws
npm ERR! prepareGitDep > node-gyp rebuild > build_log.txt 2>&1 || exit 0
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > wd@1.6.0 install /home/nimiq/.npm/_cacache/tmp/git-clone-f05fd6e2/node_modules/wd
npm ERR! prepareGitDep > node scripts/build-browser-scripts
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > leveldown@1.9.0 install /home/nimiq/.npm/_cacache/tmp/git-clone-f05fd6e2/node_modules/leveldown
npm ERR! prepareGitDep > prebuild-install || node-gyp rebuild
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated babel-preset-es2017@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm ERR! prepareGitDep npm WARN deprecated babel-preset-es2016@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm ERR! prepareGitDep npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm ERR! prepareGitDep npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! prepareGitDep npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm ERR! prepareGitDep npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm ERR! prepareGitDep npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! prepareGitDep npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! prepareGitDep npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! prepareGitDep prebuild-install info begin Prebuild-install version 2.5.1
npm ERR! prepareGitDep prebuild-install info looking for local prebuild @ prebuilds/leveldown-v1.9.0-node-v59-linux-x64.tar.gz
npm ERR! prepareGitDep prebuild-install info looking for cached prebuild @ /home/nimiq/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.9.0-leveldown-v1.9.0-node-v59-linux-x64.tar.gz
npm ERR! prepareGitDep prebuild-install http request GET https://github.com/level/leveldown/releases/download/v1.9.0/leveldown-v1.9.0-node-v59-linux-x64.tar.gz
npm ERR! prepareGitDep prebuild-install http 404 https://github.com/level/leveldown/releases/download/v1.9.0/leveldown-v1.9.0-node-v59-linux-x64.tar.gz
npm ERR! prepareGitDep prebuild-install WARN install No prebuilt binaries found (target=9.7.1 runtime=node arch=x64 platform=linux)
npm ERR! prepareGitDep Traceback (most recent call last):
npm ERR! prepareGitDep   File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 13, in <module>
npm ERR! prepareGitDep     import gyp
npm ERR! prepareGitDep   File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 8, in <module>
npm ERR! prepareGitDep     import gyp.input
npm ERR! prepareGitDep   File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 5, in <module>
npm ERR! prepareGitDep     from compiler.ast import Const
npm ERR! prepareGitDep ImportError: No module named compiler.ast
npm ERR! prepareGitDep gyp ERR! configure error
npm ERR! prepareGitDep gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! prepareGitDep gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
npm ERR! prepareGitDep gyp ERR! stack     at ChildProcess.emit (events.js:127:13)
npm ERR! prepareGitDep gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
npm ERR! prepareGitDep gyp ERR! System Linux 4.4.0-116-generic
npm ERR! prepareGitDep gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! prepareGitDep gyp ERR! cwd /home/nimiq/.npm/_cacache/tmp/git-clone-f05fd6e2/node_modules/leveldown
npm ERR! prepareGitDep gyp ERR! node -v v9.7.1
npm ERR! prepareGitDep gyp ERR! node-gyp -v v3.6.2
npm ERR! prepareGitDep gyp ERR! not ok
npm ERR! prepareGitDep npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm ERR! prepareGitDep npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! leveldown@1.9.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the leveldown@1.9.0 install script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /home/nimiq/.npm/_logs/2018-03-06T20_30_12_088Z-debug.log
npm ERR! prepareGitDep
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: jungle-db@github:nimiq-network/jungle-db#v0.3.6-luna.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nimiq/.npm/_logs/2018-03-06T20_30_12_311Z-debug.log
```

**Comment by crebuh** [comment] 2018-03-12 09:24
@jsappme 

same for me ...

**Comment by paberr** [comment] 2018-04-08 00:07
Does the problem still occur when compiling the code on our master branch?

**Comment by iPLEOMAX** [comment] 2018-04-10 12:02
Never got away with that error on Windows.

**Comment by jeffesquivels** [comment] 2018-04-12 16:10
@iPLEOMAX is it the same error or a different one? Because there's currently a known compilation but in Windows in one of our dependencies and that may be the problem you're seeing.

**Comment by iPLEOMAX** [comment] 2018-04-12 16:48
@jeffesquivels My bad, multiple tabs confused me. I was referring to the error caused by Visual Studio on node-lmdb. Not this one, thanks for pointing out.

**Comment by jeffesquivels** [comment] 2018-04-12 20:12
@iPLEOMAX no problem, that node-lmdb issue is known and reported to upstream and we're already working on a workaround and hopefully a more permanent solution.

**Closed by jeffesquivels** 2018-04-12 20:12 UTC
